#!/usr/bin/env python3
"""Regenerate _redirects: one forced 301 per page, .html -> extensionless.

Netlify's Pretty URLs post-processing is disabled on this site, so without
these rules both /foo.html and /foo return 200 and Google indexes both.

Run after adding or renaming pages:

    python3 build-redirects.py

The trailing "!" forces the redirect. Netlify skips an unforced rule when a
file already exists at the source path, and every .html file does exist, so
the force flag is what makes these fire at all.
"""
import glob

# Google Search Console fetches this exact path; redirecting it breaks
# verification.
SKIP = {"google585d8a6ecd08e358.html"}

VANITY = """# Short vanity URLs
/quiz              /games/emoji-quiz              301
/memory            /games/emoji-memory            301
/tick-tac-toe      /games/emoji-tick-tac-toe      301
/globe             /emojie_globe/globe            301
/blog              /blogs/blog                    301
/search            /emoji-search                  301

# Legacy path
/games.html        /games/games                   301!
"""

HEADER = """
# Canonical URL form: strip .html.
#
# Netlify's Pretty URLs post-processing is off on this site, so /foo.html and
# /foo both returned 200 - duplicate content on every page, and Google has
# indexed both forms. These rules collapse them onto the extensionless URL that
# every canonical tag points at.
#
# The "!" (force) matters: the .html files physically exist, and without it
# Netlify serves the file instead of redirecting. Generated by build-redirects.py.
"""


def main():
    rules = []
    for f in sorted(glob.glob("**/*.html", recursive=True)):
        if f in SKIP:
            continue
        rules.append(("/" + f, "/" if f == "index.html" else "/" + f[:-5]))

    # A destination that is also a source would be a redirect loop.
    sources = {s for s, _ in rules}
    loops = [(s, d) for s, d in rules if d in sources]
    if loops:
        raise SystemExit(f"refusing to write: redirect loops {loops}")

    width = max(len(s) for s, _ in rules) + 2
    body = "\n".join(f"{s:<{width}}{d:<{width}}301!" for s, d in rules)
    open("_redirects", "w", encoding="utf-8").write(f"{VANITY}{HEADER}{body}\n")
    print(f"_redirects: {len(rules)} forced .html -> extensionless rules")


if __name__ == "__main__":
    main()
