// ...existing code...
(function () {
    'use strict';

    // Config: production-level single source of truth for emojis
    // We use the enhanced file generated by scripts/enhance_emojis.py
    const DATA_PATHS = ['/emojis.enhanced.json'];

    // Helpers
    const el = (tag, cls) => { const e = document.createElement(tag); if (cls) e.className = cls; return e; };

    let openEmojiDropdown = null;

    function closeOpenEmojiDropdown(target) {
        if (!openEmojiDropdown) return;
        if (target && openEmojiDropdown.root.contains(target)) return;
        openEmojiDropdown.close({ focusTrigger: false });
    }

    document.addEventListener('click', event => closeOpenEmojiDropdown(event.target));
    document.addEventListener('keydown', event => {
        if (event.key === 'Escape') {
            closeOpenEmojiDropdown();
        }
    });

    function createEmojiDropdown({ rootClass = '' } = {}) {
        const root = el('div', `emoji-dropdown ${rootClass}`.trim());
        const trigger = el('button', 'emoji-dropdown__trigger');
        trigger.type = 'button';
        trigger.setAttribute('aria-haspopup', 'listbox');
        trigger.setAttribute('aria-expanded', 'false');
        trigger.setAttribute('aria-label', 'Select an option');
        const valueEl = el('span', 'emoji-dropdown__value');
        trigger.appendChild(valueEl);
        root.appendChild(trigger);

        const menu = el('div', 'emoji-dropdown__menu');
        menu.setAttribute('role', 'listbox');
        root.appendChild(menu);

        let options = [];
        let currentValue = null;
        const listeners = [];
        let api;

        function notify(newValue, meta) {
            listeners.forEach(cb => {
                try { cb(newValue, meta); } catch (err) { console.error(err); }
            });
        }

        function setValue(newValue, { emit = true } = {}) {
            if (newValue === undefined || newValue === null) return;
            const option = options.find(opt => opt.value === newValue);
            if (!option) return;

            currentValue = newValue;
            valueEl.textContent = option.label ?? option.value ?? '';
            const ariaLabel = option.ariaLabel || option.title || option.label || option.value;
            trigger.setAttribute('aria-label', ariaLabel ? `Filter by ${ariaLabel}` : 'Select an option');
            root.dataset.value = newValue;

            options.forEach(opt => {
                if (!opt.button) return;
                const selected = opt.value === newValue;
                opt.button.classList.toggle('emoji-dropdown__option--selected', selected);
                opt.button.setAttribute('aria-selected', selected);
            });

            if (emit) {
                notify(newValue, option);
            }
        }

        function close({ focusTrigger = false } = {}) {
            root.classList.remove('emoji-dropdown--open');
            trigger.setAttribute('aria-expanded', 'false');
            if (focusTrigger) {
                trigger.focus({ preventScroll: true });
            }
            if (openEmojiDropdown === api) {
                openEmojiDropdown = null;
            }
        }

        function open() {
            if (openEmojiDropdown && openEmojiDropdown !== api) {
                openEmojiDropdown.close();
            }
            root.classList.add('emoji-dropdown--open');
            trigger.setAttribute('aria-expanded', 'true');
            openEmojiDropdown = api;
        }

        function toggle() {
            if (root.classList.contains('emoji-dropdown--open')) {
                close();
            } else {
                open();
            }
        }

        function setOptions(items = [], { defaultValue, emit = false } = {}) {
            options = items.map(opt => ({ ...opt }));
            menu.innerHTML = '';
            const frag = document.createDocumentFragment();
            options.forEach(opt => {
                const btn = el('button', 'emoji-dropdown__option');
                btn.type = 'button';
                btn.dataset.value = opt.value;
                btn.textContent = opt.label ?? opt.value ?? '';
                const aria = opt.ariaLabel || opt.title || opt.label || opt.value;
                if (aria) {
                    btn.setAttribute('aria-label', aria);
                }
                btn.addEventListener('click', () => {
                    setValue(opt.value);
                    close({ focusTrigger: false });
                });
                opt.button = btn;
                frag.appendChild(btn);
            });
            menu.appendChild(frag);

            const fallback = (defaultValue && options.some(opt => opt.value === defaultValue))
                ? defaultValue
                : options[0]?.value;
            if (fallback) {
                setValue(fallback, { emit });
            }
        }

        function onChange(cb) {
            if (typeof cb === 'function') {
                listeners.push(cb);
            }
        }

        trigger.addEventListener('click', event => {
            event.stopPropagation();
            toggle();
        });

        trigger.addEventListener('keydown', event => {
            if (event.key === 'ArrowDown') {
                event.preventDefault();
                open();
                const selected = options.find(opt => opt.value === currentValue);
                selected?.button?.focus({ preventScroll: true });
            }
        });

        menu.addEventListener('click', event => event.stopPropagation());

        api = {
            root,
            trigger,
            menu,
            setOptions,
            setValue,
            getValue: () => currentValue,
            onChange,
            close,
            open,
        };

        return api;
    }

    // Find the emoji grid container in your index.html
    const container = document.querySelector('.emoji-grid');
    if (!container) return;

    // Build UI (controls + list + toast)
    const controls = el('div', 'emoji-controls');
    const searchInput = el('input', 'emoji-search');
    searchInput.type = 'search';
    searchInput.placeholder = 'Search emojis';
    searchInput.setAttribute('aria-label', 'Search emojis');

    const categoryDropdown = createEmojiDropdown({ rootClass: 'emoji-category-dropdown' });
    categoryDropdown.trigger.setAttribute('aria-label', 'Filter by category');

    // NOTE: skin tone selector removed — we now use enhanced tags in the data for tone-specific searches

    const count = el('span', 'emoji-count');
    count.setAttribute('aria-live', 'polite');

    const searchSlot = container.querySelector('.emoji-grid__search-slot');
    if (searchSlot) {
        searchSlot.appendChild(searchInput);
    } else {
        controls.appendChild(searchInput);
    }

    // Prevent iOS from zooming the page when the search input is focused
    // Strategy: increase input font-size to 16px on touch/focus (iOS zoom happens when font-size < 16px)
    (function preventMobileZoomOnInput() {
        try {
            const isiOS = /iP(ad|hone|od)/.test(navigator.userAgent) && !window.MSStream;
            if (!isiOS) return;
            const originalSize = searchInput.style.fontSize || '';
            function apply() {
                // only set if computed font-size is less than 16px
                const comp = window.getComputedStyle(searchInput).fontSize || '16px';
                const px = parseFloat(comp);
                if (px < 16) searchInput.style.fontSize = '16px';
            }
            function restore() {
                if (originalSize) searchInput.style.fontSize = originalSize; else searchInput.style.fontSize = '';
            }
            searchInput.addEventListener('touchstart', apply, { passive: true });
            searchInput.addEventListener('focus', apply);
            searchInput.addEventListener('blur', restore);
        } catch (e) {
            // fail silently
        }
    })();
    const filtersContainer = container.querySelector('.emoji-grid__filters');
    const categorySlot = container.querySelector('.emoji-grid__category-slot');
    if (categorySlot) {
        categorySlot.appendChild(categoryDropdown.root);
    } else {
        controls.appendChild(categoryDropdown.root);
    }
    const countSlot = container.querySelector('.emoji-grid__count-slot');
    if (countSlot) {
        countSlot.appendChild(count);
    } else {
        controls.appendChild(count);
    }

    const list = el('div', 'emoji-list');
    list.setAttribute('role', 'list');

    const toast = el('div', 'emoji-toast');
    toast.setAttribute('aria-hidden', 'true');
    document.body.appendChild(toast);

    container.appendChild(controls);
    container.appendChild(list);

    function applyResponsiveLayout() {
        if (!filtersContainer) return;
        if (window.innerWidth <= 720) {
            filtersContainer.style.display = 'flex';
            filtersContainer.style.flexDirection = 'row';
            filtersContainer.style.flexWrap = 'nowrap';
            filtersContainer.style.alignItems = 'center';
            filtersContainer.style.gap = '8px';
            filtersContainer.style.marginLeft = '0';
            filtersContainer.style.width = '100%';
            if (searchSlot) {
                searchSlot.style.flex = '1 1 0%';
                searchSlot.style.minWidth = '0';
            }
            if (categorySlot) {
                categorySlot.style.flex = '0 0 auto';
                categorySlot.style.width = 'auto';
            }
            categoryDropdown.root.style.width = '56px';
            categoryDropdown.root.style.minWidth = '56px';
        } else {
            filtersContainer.style.display = '';
            filtersContainer.style.flexDirection = '';
            filtersContainer.style.flexWrap = '';
            filtersContainer.style.alignItems = '';
            filtersContainer.style.gap = '';
            filtersContainer.style.marginLeft = '';
            filtersContainer.style.width = '';
            if (searchSlot) {
                searchSlot.style.flex = '';
                searchSlot.style.minWidth = '';
            }
            if (categorySlot) {
                categorySlot.style.flex = '';
                categorySlot.style.width = '';
            }
            categoryDropdown.root.style.width = '';
            categoryDropdown.root.style.minWidth = '';
        }
    }

    window.addEventListener('resize', applyResponsiveLayout);
    applyResponsiveLayout();

    // Minimal styles injection (optional, keeps everything working without editing CSS)
    const style = document.createElement('style');
    style.textContent = `
    .emoji-grid__header { display:flex; justify-content:space-between; align-items:center; gap:32px; flex-wrap:nowrap; }
    .emoji-grid__title { display:flex; flex-direction:column; gap:10px; min-width:0; }
    .emoji-grid__breadcrumb { font-size:12px; letter-spacing:0.28em; text-transform:uppercase; font-weight:600; color:#ff7926; opacity:0.9; }
    .emoji-grid__heading { margin:0; display:flex; gap:14px; font-size:clamp(34px,4vw,48px); font-weight:800; text-transform:uppercase; letter-spacing:0.08em; color:#fff; }
    .emoji-grid__heading span:first-child { color:#f8fafc; }
    .emoji-grid__heading span:last-child { color:#ff5500; }
    .emoji-grid__filters { display:flex; align-items:center; gap:14px; margin-left:auto; flex:1 1 auto; max-width:480px; }
    .emoji-grid__search-slot { position:relative; flex:1 1 clamp(240px,32vw,420px); min-width:220px; max-width:420px; }
    .emoji-grid__category-slot { flex:0 0 auto; display:flex; align-items:center; }
    .emoji-grid__count-slot { min-height:20px; }
    .emoji-grid__search-slot::before { content:"\\1F50D"; position:absolute; left:20px; top:50%; transform:translateY(-50%); font-size:18px; opacity:0.6; pointer-events:none; }
    .emoji-grid__search-slot .emoji-search { width:100%; border-radius:0; padding:16px 20px 16px 58px; min-height:44px; box-sizing:border-box; background:rgba(15,15,17,0.92); border:1px solid rgba(255,255,255,0.08); color:#f9fafb; letter-spacing:0.28em; text-transform:uppercase; font-size:12px; font-weight:600; transition:border-color 0.2s ease, box-shadow 0.2s ease; }
    .emoji-grid__search-slot .emoji-search::placeholder { color:#6b7280; }
    .emoji-grid__search-slot .emoji-search:focus { outline:none; border-color:rgba(255,119,51,0.65); box-shadow:0 0 0 2px rgba(255,119,51,0.2); }
    .emoji-controls { display:flex; flex-wrap:wrap; gap:4px; align-items:center; margin-bottom:4px; padding-top:4px; border-top:none; }
    .emoji-controls:empty { display:none; }
    .emoji-dropdown { position:relative; display:inline-flex; width:64px; min-width:64px; flex-shrink:0; --dropdown-width:100%; }
    .emoji-dropdown__trigger { width:100%; min-height:44px; padding:10px 0; border-radius:0; border:1px solid rgba(255,255,255,0.12); box-sizing:border-box; background:rgba(5,5,6,0.92); color:#f8fafc; font-size:24px; line-height:1; display:flex; align-items:center; justify-content:center; cursor:pointer; transition:border-color 0.18s ease, box-shadow 0.18s ease, background 0.18s ease; }
    .emoji-dropdown__trigger:focus-visible,
    .emoji-dropdown--open .emoji-dropdown__trigger { outline:none; border-color:#2563eb; box-shadow:0 0 0 3px rgba(37,99,235,0.35); background:rgba(7,7,10,0.98); }
    .emoji-dropdown__value { pointer-events:none; }
    .emoji-dropdown__menu { position:absolute; top:calc(100% + 10px); left:0; width:var(--dropdown-width); min-width:var(--dropdown-width); max-width:var(--dropdown-width); background:rgba(12,12,13,0.98); border:1px solid rgba(255,255,255,0.08); border-radius:0; padding:6px 0; box-shadow:0 20px 48px rgba(5,5,6,0.54); opacity:0; transform:translateY(-6px) scale(0.96); pointer-events:none; transition:opacity 0.16s ease, transform 0.16s ease; z-index:1400; max-height:260px; overflow-y:auto; overflow-x:hidden; }
    .emoji-dropdown--open .emoji-dropdown__menu { opacity:1; transform:translateY(0) scale(1); pointer-events:auto; }
    .emoji-dropdown__option { width:100%; border:none; background:transparent; font-size:24px; line-height:1; color:#f8fafc; display:flex; align-items:center; justify-content:center; padding:10px 0; cursor:pointer; transition:background 0.16s ease, color 0.16s ease; }
    .emoji-dropdown__option:hover { background:rgba(255,77,0,0.14); color:#ff7926; }
    .emoji-dropdown__option--selected,
    .emoji-dropdown__option[aria-selected="true"] { background:linear-gradient(135deg, rgba(37,99,235,0.28), rgba(59,130,246,0.16)); color:#9ac4ff; }
    .emoji-count { display:inline-flex; font-size:12px; color:#94a3b8; letter-spacing:0.24em; text-transform:uppercase; font-weight:600; }
    .emoji-list { display:grid; grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); gap:12px; justify-content:center; justify-items:center; }
    .emoji-btn { display:flex; flex-direction:column; align-items:center; justify-content:center; padding:8px; height:75px;width:100px; border:1px solid #222; background:black; cursor:pointer; transition:background-color .2s ease, border-color .2s ease; }
    .emoji-btn:hover { background:#ff4d00; border-color:#ff4d00; }
    .emoji-char { font-size:28px; line-height:1; }
    .emoji-name { font-size:12px; color:#333; margin-top:6px; text-align:center; word-break:break-word; }
    .emoji-toast { position:fixed; left:50%; transform:translateX(-50%); bottom:20px; background:#222; color:#fff; padding:8px 12px;  opacity:0; transition:opacity .15s; pointer-events:none; font-size:13px; z-index:9999; }
    .emoji-toast.visible { opacity:1; }
    @media(max-width:720px){
        .emoji-grid__header { flex-direction:column; align-items:flex-start; gap:6px; }
        .emoji-grid__title { gap:3px; }
    .emoji-grid__filters { width:100%; display:flex; flex-direction:row; align-items:center; gap:3px; max-width:none; flex-wrap:nowrap; margin-top:0; }
    .emoji-grid__count-slot { min-height:0; margin-top:0; }
    .emoji-grid__search-slot { flex:1 1 auto; min-width:0; max-width:none; }
    .emoji-grid__category-slot { flex:0 0 auto; }
    .emoji-grid__search-slot::before { left:16px; }
    .emoji-grid__search-slot .emoji-search { padding:14px 18px 14px 52px; min-height:42px; font-size:11px; letter-spacing:0.24em; border-radius:0; }
    .emoji-dropdown { width:56px; min-width:56px; }
    .emoji-dropdown__trigger { min-height:42px; font-size:22px; }
    .emoji-count { margin-left:0; margin-top:0; }
    .emoji-controls { margin-bottom:0; padding-top:0; gap:4px; border-top:none; }
        .emoji-list { grid-template-columns: repeat(3, minmax(0, 1fr)); }
    }
    @media(max-width:360px){
    .emoji-grid__filters { gap:6px; }
    .emoji-dropdown { width:48px; min-width:48px; }
    .emoji-dropdown__trigger { min-height:40px; font-size:20px; padding:8px 0; }
    .emoji-grid__search-slot .emoji-search { min-height:40px; }
    }
    `;
    document.head.appendChild(style);

    // Load data (try multiple paths)
    async function loadData() {
        const cacheKey = 'emojiData.v1';
        try {
            const cached = localStorage.getItem(cacheKey);
            if (cached) {
                const json = JSON.parse(cached);
                if (Array.isArray(json)) return json;
            }
        } catch (e) {
            // ignore cache errors and fall through to network
        }

        for (const path of DATA_PATHS) {
            try {
                const res = await fetch(path, { cache: "force-cache" });
                if (!res.ok) continue;
                // read as text so we can attempt to cache the raw payload
                const txt = await res.text();
                try {
                    // try to persist to localStorage if size is reasonable
                    const byteLen = new Blob([txt]).size;
                    if (byteLen < 2500000) { // avoid exceeding typical localStorage limits
                        try { localStorage.setItem(cacheKey, txt); } catch (err) { /* ignore */ }
                    }
                } catch (err) { /* ignore */ }
                const json = JSON.parse(txt);
                if (Array.isArray(json)) return json;
            } catch (e) {
                // try next
            }
        }
        throw new Error('emojis.json not found or invalid');
    }

    // Category inference map: production-friendly categories and keywords to match
    const CATEGORY_KEYWORDS = [
        { name: 'Smileys', keys: ['face', 'grinning', 'smiling', 'tear', 'joy', 'heart', 'star', 'smile', 'cry', 'laugh'] },
        { name: 'People', keys: ['person', 'man', 'woman', 'boy', 'girl', 'hand', 'thumb', 'fist', 'pray', 'person', 'police', 'doctor'] },
        { name: 'Animals', keys: ['dog', 'cat', 'animal', 'lion', 'tiger', 'monkey', 'nature', 'flower', 'plant', 'tree'] },
        { name: 'Food', keys: ['food', 'drink', 'pizza', 'apple', 'cake', 'fork', 'spoon'] },
        { name: 'Activities', keys: ['sport', 'ball', 'golf', 'run', 'dance', 'party', 'game'] },
        { name: 'Travel', keys: ['car', 'train', 'plane', 'house', 'hotel', 'map', 'bridge', 'beach'] },
        { name: 'Objects', keys: ['phone', 'computer', 'book', 'light', 'tool', 'watch', 'camera'] },
        { name: 'Symbols', keys: ['symbol', 'sign', 'warning', 'arrow', 'heart', 'star'] },
        { name: 'Flags', keys: ['flag'] }
    ];

    function inferCategory(item) {
        const text = ((item.name || '') + ' ' + (item.tags || []).join(' ')).toLowerCase();
        for (const cat of CATEGORY_KEYWORDS) {
            for (const k of cat.keys) {
                if (text.includes(k)) return cat.name;
            }
        }
        return 'Other';
    }

    // Skin tone helper: given a base emoji string, return modified emoji with skin tone modifier appended
    function applySkinTone(base, toneHex) {
        if (!toneHex || toneHex === 'default') return base;
        try {
            // Clean and get code points for base
            const cps = Array.from(base).map(ch => ch.codePointAt(0));
            // Append modifier at the end of base if heuristic: base likely a person/hand
            const modifier = parseInt(toneHex, 16);
            return String.fromCodePoint(...cps, modifier);
        } catch (e) {
            return base;
        }
    }

    // Heuristic: check whether an emoji likely supports skin tone based on name/tags
    function supportsSkinTone(item) {
        // Only apply skin tone modifiers to emojis that are single base glyphs and are known to support modifiers
        const base = normalizeEmojiChar(item.emoji || item.char || '');
        const codepoints = Array.from(base).map(ch => ch.codePointAt(0));
        // If the base is multiple codepoints (ZWJ sequences, flags, faces-with-hand), don't apply
        if (codepoints.length !== 1) return false;

        // Whitelist of general categories that accept modifiers (hands and people)
        const whitelistRanges = [
            // hands/fingers: U+270A .. U+270D (fist, raised hand, etc) and U+1F44B..U+1F450
            [0x270A, 0x270D],
            [0x1F44B, 0x1F450]
        ];
        const cp = codepoints[0];
        for (const [lo, hi] of whitelistRanges) {
            if (cp >= lo && cp <= hi) return true;
        }

        // also allow gendered person emojis in BMP Supplement ranges (simple check)
        // common person emojis like U+1F464 (bust in silhouette) or U+1F466..U+1F469
        const extra = [0x1F466, 0x1F467, 0x1F468, 0x1F469, 0x1F9D1];
        if (extra.includes(cp)) return true;

        return false;
    }

    function showToast(text) {
        toast.textContent = text;
        toast.setAttribute('aria-hidden', 'false');
        toast.classList.add('visible');
        clearTimeout(toast._timeout);
        toast._timeout = setTimeout(() => {
            toast.classList.remove('visible');
            toast.setAttribute('aria-hidden', 'true');
        }, 1100);
    }

    function copyText(text) {
        if (navigator.clipboard && navigator.clipboard.writeText) {
            return navigator.clipboard.writeText(text);
        }
        // fallback
        const ta = document.createElement('textarea');
        ta.value = text;
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.select();
        try { document.execCommand('copy'); } catch (e) { /* ignore */ }
        ta.remove();
        return Promise.resolve();
    }

    // Normalize various emoji representations into actual emoji characters.
    // Handles:
    // - already-present emoji characters
    // - JSON/JS escaped strings like "\\uD83D\\uDE00" or "\uD83D\uDE00"
    // - codepoint strings like "U+1F600", "1F600", "0x1F600"
    // - sequences like "1F468-200D-1F469-200D-1F466"
    function normalizeEmojiChar(s) {
        if (!s && s !== 0) return '';
        const raw = String(s).trim();

        // If it already contains a non-ascii glyph (likely an emoji), return as-is
        if (/[^ -]/.test(raw)) return raw;

        // Try JSON-style escaped sequences ("\uD83D\uDE00" or "\\uD83D\\uDE00")
        try {
            if (/\\u/i.test(raw)) {
                // Ensure proper quoting for JSON.parse
                return JSON.parse('"' + raw.replace(/"/g, '\\"') + '"');
            }
        } catch (e) { /* fall through */ }

        // Normalize common prefixes and separators to get hex codepoint groups
        // Examples: "U+1F600", "1F600", "0x1F600", "1F468-200D-1F469-200D-1F466"
        const cleaned = raw.replace(/^u\+/i, '')
            .replace(/^0x/i, '')
            .replace(/[^0-9A-Fa-f]+/g, ' ')
            .trim();
        if (!cleaned) return raw;

        const parts = cleaned.split(/\s+/);
        try {
            const cps = parts.map(p => parseInt(p, 16)).filter(n => !Number.isNaN(n));
            if (cps.length) return String.fromCodePoint(...cps);
        } catch (e) { /* ignore */ }

        return raw;
    }

    // Simple debounce helper to reduce excessive filtering on fast input
    function debounce(fn, wait) {
        let t = null;
        return function (...args) {
            clearTimeout(t);
            t = setTimeout(() => fn.apply(this, args), wait);
        };
    }

    // Render list of emojis (production-ready incremental renderer)
    let renderList;
    (function () {
        // Adaptive chunk size: smaller on narrow screens
        function getChunkSize() {
            if (typeof navigator !== 'undefined' && navigator.hardwareConcurrency) {
                // fewer chunks on low-core devices
                const cores = navigator.hardwareConcurrency || 4;
                return window.innerWidth <= 480 ? Math.max(32, Math.floor(cores * 8)) : Math.max(80, Math.floor(cores * 24));
            }
            return window.innerWidth <= 480 ? 48 : 120;
        }

        let CHUNK_SIZE = getChunkSize();
        // Recompute chunk size on resize (debounced)
        let resizeTimer = null;
        window.addEventListener('resize', () => {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(() => { CHUNK_SIZE = getChunkSize(); }, 250);
        });

        let state = { items: [], index: 0 };
        const sentinel = document.createElement('div');
        sentinel.className = 'emoji-list-sentinel';
        sentinel.setAttribute('aria-hidden', 'true');

        function createEmojiButton(it) {
            const btn = el('button', 'emoji-btn');
            btn.type = 'button';
            btn.setAttribute('role', 'listitem');
            const normalizedBase = normalizeEmojiChar(it.emoji || it.char || '');
            const displayChar = normalizedBase;
            btn.setAttribute('aria-label', `${it.name || displayChar || 'emoji'} — click to copy`);
            const spanChar = el('span', 'emoji-char');
            spanChar.textContent = displayChar || '?';
            btn.appendChild(spanChar);
            btn.addEventListener('click', async () => {
                try {
                    await copyText(displayChar || '');
                    showToast(`Copied ${displayChar || ''}`);
                } catch (e) {
                    showToast('Copy failed');
                }
            });
            return btn;
        }

        // Use requestIdleCallback when available for background chunk work
        const idle = window.requestIdleCallback ? window.requestIdleCallback.bind(window) : (fn) => setTimeout(fn, 50);

        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    // load next chunk during idle time to avoid jank
                    idle(() => appendChunk());
                }
            });
        }, { root: null, rootMargin: '600px', threshold: 0.01 });

        function appendChunk() {
            if (!state.items || state.index >= state.items.length) {
                if (sentinel.parentNode) sentinel.remove();
                return;
            }

            const end = Math.min(state.items.length, state.index + CHUNK_SIZE);
            const frag = document.createDocumentFragment();
            for (let i = state.index; i < end; i++) {
                frag.appendChild(createEmojiButton(state.items[i]));
            }

            // Batch DOM insertion on next animation frame and only then attach sentinel
            requestAnimationFrame(() => {
                list.appendChild(frag);
                state.index = end;

                if (state.index < state.items.length) {
                    if (!sentinel.parentNode) list.appendChild(sentinel);
                    observer.observe(sentinel);
                } else {
                    if (sentinel.parentNode) sentinel.remove();
                    try { observer.unobserve(sentinel); } catch (e) { /* ignore */ }
                }
            });
        }

        function clearRender() {
            // Remove sentinel and reset state
            try { observer.unobserve(sentinel); } catch (e) { /* ignore */ }
            if (sentinel.parentNode) sentinel.remove();
            state = { items: [], index: 0 };
        }

        function render(items) {
            clearRender();
            state.items = Array.isArray(items) ? items : [];
            state.index = 0;
            list.innerHTML = '';
            count.textContent = state.items.length ? `${state.items.length} shown` : 'No emojis found';

            if (!state.items.length) return;

            // Insert the first chunk immediately so the user sees content right away
            appendChunk();
            // subsequent chunks will be loaded via IntersectionObserver + idle
        }

        // expose
        renderList = render;
        window.__emojiRenderList = render;
    })();

    // Filtering logic
    function createFilter(all) {
        return function filter() {
            const q = searchInput.value.trim().toLowerCase();
            const cat = categoryDropdown.getValue();
            // skin-tone removed; simple search by query and category
            const filtered = all.filter(e => {
                if (cat && cat !== 'all' && ((e.category || 'Uncategorized') !== cat)) return false;
                if (!q) return true;
                // 1) match full name substring
                if ((e.name || '').toLowerCase().includes(q)) return true;
                // 2) match any tag substring
                if ((e.tags || []).some(t => String(t).toLowerCase().includes(q))) return true;
                // 3) match tokens (hex, synonyms, base glyph)
                for (const t of e._tokens || []) {
                    try {
                        if (String(t).toLowerCase().includes(q)) return true;
                    } catch (err) { /* ignore */ }
                }
                // 4) match the emoji glyph directly
                if ((e._base || '').toLowerCase().includes(q)) return true;
                return false;
            });
            renderList(filtered);
        };
    }

    // Initialize
    (async function init() {
        try {
            const all = await loadData();

            // populate categories
            // build search tokens and infer categories
            all.forEach(e => {
                const base = normalizeEmojiChar(e.emoji || e.char || '');
                e._base = base;
                const nameWords = (e.name || '').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
                const tagWords = (e.tags || []).map(t => String(t).toLowerCase());
                const cpHex = Array.from(base).map(ch => ch.codePointAt(0).toString(16));
                // start tokens from name, tags, base and codepoints
                // also include any explicit search tokens/keywords present in the JSON
                const extraFromJson = [
                    ...(e.search_tokens || []).map(t => String(t).toLowerCase()),
                    ...(e.keywords || []).map(t => String(t).toLowerCase())
                ];
                const tokens = new Set([...nameWords, ...tagWords, base, ...cpHex, ...extraFromJson]);

                // Add helpful synonyms and compound tokens for better search
                if ((nameWords.includes('hand') || tagWords.includes('hand'))) {
                    tokens.add('hand');
                    tokens.add('right hand');
                    tokens.add('left hand');
                    tokens.add('raised hand');
                    tokens.add('dark hand');
                    tokens.add('light hand');
                    tokens.add('skin tone');
                    tokens.add('hand right');
                    tokens.add('hand left');
                }
                if ((nameWords.includes('man') || nameWords.includes('woman') || tagWords.includes('person') || tagWords.includes('man') || tagWords.includes('woman'))) {
                    tokens.add('person');
                    tokens.add('man');
                    tokens.add('woman');
                    tokens.add('male');
                    tokens.add('female');
                    tokens.add('skin tone');
                    tokens.add('light skin');
                    tokens.add('dark skin');
                }
                // Add directional words frequently searched
                if (nameWords.includes('left') || nameWords.includes('right') || tagWords.includes('left') || tagWords.includes('right')) {
                    tokens.add('left'); tokens.add('right');
                }

                e._tokens = Array.from(tokens);
                e.category = e.category || inferCategory(e);
            });
            // Deduplicate by base emoji: merge entries with same base into one representative
            const dedupeMap = new Map();
            for (const e of all) {
                const base = e._base || normalizeEmojiChar(e.emoji || e.char || '');
                const key = base || (e.name || '').toLowerCase();
                if (!dedupeMap.has(key)) {
                    // clone minimal structure
                    dedupeMap.set(key, {
                        emoji: base,
                        name: e.name || '',
                        tags: Array.from(new Set(e.tags || [])),
                        _tokens: Array.from(new Set(e._tokens || [])),
                        category: e.category || 'Other',
                        _originals: [e]
                    });
                } else {
                    const cur = dedupeMap.get(key);
                    // prefer longer/more descriptive name
                    if (!cur.name && e.name) cur.name = e.name;
                    // merge tags and tokens
                    cur.tags = Array.from(new Set([...(cur.tags || []), ...(e.tags || [])]));
                    cur._tokens = Array.from(new Set([...(cur._tokens || []), ...(e._tokens || [])]));
                    if (!cur.category && e.category) cur.category = e.category;
                    cur._originals.push(e);
                }
            }
            const deduped = Array.from(dedupeMap.values());
            const cats = Array.from(new Set(deduped.map(e => e.category)));
            const dropdownOptions = [{
                value: 'all',
                label: '🌐',
                ariaLabel: 'All categories',
                title: 'All categories'
            }];

            // icon map (normalized to lowercase for matching dataset/category variations)
            const CATEGORY_ICONS = {
                'smileys & emotion': '😀',
                'smileys': '😀',
                'people & body': '🧑',
                'people': '🧑',
                'animals & nature': '🐶',
                'animals': '🐶',
                'food & drink': '🍔',
                'food': '🍔',
                'activities': '⚽',
                'travel & places': '✈️',
                'travel': '✈️',
                'objects': '📱',
                'symbols': '🔣',
                'flags': '🏳️',
                'other': '🔸'
            };

            cats.forEach(c => {
                const icon = CATEGORY_ICONS[(c || '').toLowerCase()] || '🔹';
                dropdownOptions.push({
                    value: c,
                    label: icon,
                    ariaLabel: c || 'Category',
                    title: c || ''
                });
            });

            categoryDropdown.setOptions(dropdownOptions, { defaultValue: 'all', emit: false });

            // wire events
            // use deduped list for filtering and rendering
            const filter = createFilter(deduped);
            const scheduleFilter = debounce(filter, 120);
            searchInput.addEventListener('input', scheduleFilter);
            categoryDropdown.onChange(() => scheduleFilter());
            // no skin-tone UI any more

            // initial render
            filter();
        } catch (err) {
            list.textContent = 'Failed to load emojis data.';
            console.error(err);
        }
    })();

})();